### ISSUE TITLE
File path not created

### ISSUE THREAD

**Issue by stephenc222** [dcbarrett/vscode-coffeescript-preview#3]
Running a Windows 10 home, VSC version 1.8.1 CoffeeScript Preview version 0.1.3. CoffeeScript Preview correctly generates compiled JavaScript from CoffeeScript, however CoffeeScript Preview is unable to create a filename or filepath, resulting in the file displayed as plain text instead of JavaScript. Please advise.

**Comment by dcbarrett** [comment]
Thanks for opening the issue. I see you submitted a PR to resolve the issue. 👍 
Once the PR is ready to go, I'll do another release.

**Comment by dcbarrett** [comment]
This issue has been resolved and will be in the 0.1.4 release.
